language: node_js
node_js:
- lts/*
sudo: required
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
install:
cache:
  yarn: true
  npm: true
  directories:
  - backend/node_modules
  - frontend/node_modules
script:
- echo 'Testing Backend Project'
- cd ./backend
- yarn install && yarn test:cov
- cd ../frontend
- echo 'Testing FE Project'
- yarn install && yarn test:ci
after_success:
- bash <(curl -s https://codecov.io/bash)
# notifications:
  # slack: broskitownusa:DPJ68dsuWDAtrLTx1OyvgwVu