export enum RANDOM_PERSON_NATIONALITIES_ENUM {
  austrailia = 'AU',
  br = 'BR',
  canada = 'CA',
  ch = 'CH',
  de = 'DE',
  dk = 'DK',
  es = 'ES',
  fi = 'FI',
  fr = 'FR',
  greatBritain = 'GB',
  ie = 'IE',
  ir = 'IR',
  no = 'NO',
  nl = 'NL',
  nz = 'NZ',
  tr = 'TR',
  unitedStates = 'US',
}
