export const DISLIKES = [
  'Things Your Dog Hates',
  'Hugging',
  'Getting in a Dog\'s Face and Personal Space',
  'Not Letting a Dog Sniff and Explore on Walks',
  'Lack of Routine and Rules',
  'Yelling and Harsh Punishment',
  'Dressing Them Up',
  'Strong Fragrances',
  'Being Left Alone or Ignored',
  'Forcing Them Into Uncomfortable Situations',
  'Being Upset',
  'Using words instead of body language',
  'The smell of Peppers',
  'The smell of Citrus',
  'The smell of Vinegar',
  'The smell of Rubbing Alcohol',
  'The smell of Mothballs',
  'The smell of Privacy Policy',
  'Alcohol',
  'Apple Seeds',
  'Avocado',
  'Candy, Chewing Gum, Toothpaste & Mouthwash',
  'Cat Food',
  'Chocolate',
  'Coffee, Tea & Other Caffeine',
  'Cooked Bones',
  'Corn On The Cob',
  'Fat Trimmings',
  'Garlic',
  'Grapes & Raisins',
  'Hops',
  'Human Vitamins',
  'Liver',
  'Macadamia Nuts',
  'Marijuana',
  'Milk & Dairy Products',
  'Onions & Chives',
  'Peppers ',
  'Persimmon, Peach & Plum Pits',
  'Raw Meat & Fish',
  'Rhubarb & Tomato Leaves',
  'Salt',
  'Sugar',
  'Tobacco',
  'Xylitol',
  'Yeast',
  'Old Food',
  'Leftovers',
  'Human Snacks',
  'Lean Meat',
  'Eggs',
  'Fruits',
  'Vegetables',
  'White Rice',
];
