export const HOBBIES = [
  '3D printing',
  'About.com',
  'Acrobatics',
  'Acting',
  'Action figure',
  'Adams Media',
  'Air sports',
  'Aircraft spotting',
  'Airsoft',
  'Alcester',
  'Amateur Gardening (magazine)',
  'Amateur astronomy',
  'Amateur radio',
  'American Cryptogram Association',
  'American football',
  'Animal fancy',
  'Animation',
  'Antiquing',
  'Antiquities',
  'Aquascaping',
  'Arcadia Publishing',
  'Archery',
  'Art collecting',
  'Asheville',
  'Association football',
  'Astrological Association of Great Britain',
  'Astrology',
  'Astronomy',
  'Audiophile',
  'Australian Parkour Association',
  'Australian rules football',
  'Auto audiophilia',
  'Auto racing',
  'Aviation',
  'Axe throwing',
  'BASE jumping',
  'BBC',
  'BMX',
  'Backpacking (disambiguation)',
  'Backpacking (travel)',
  'Badminton',
  'Badminton England',
  'Baking',
  'Baseball',
  'Basketball',
  'Baton twirling',
  'Beach volleyball',
  'Beatboxing',
  'Beauty pageant',
  'Beekeeping',
  'Bird watching',
  'Birdwatching',
  'Blacksmithing',
  'Blogging',
  'Board game',
  'Board sports',
  'Boardgame Players Association',
  'Bodybuilding',
  'Book collecting',
  'Book discussion club',
  'Book restoration',
  'Bowling',
  'Boxing',
  'Brazilian jiu-jitsu',
  'Breadmaking',
  'Breakdancing',
  'British Amateur Rugby League Association',
  'British Beekeepers\' Association',
  'British Canoe Union',
  'British Cycling',
  'British Equestrian Federation',
  'British Go Association',
  'British Mountaineering Council',
  'British Mycological Society',
  'British Numismatic Society',
  'British Society of Dowsers',
  'British Sub-Aqua Club',
  'Building',
  'Bus spotting',
  'Butterfly watching',
  'CNBC',
  'CSIRO Publishing',
  'Cabaret',
  'Calligraphy',
  'Cambridge University Press',
  'Camping',
  'Canal & River Trust',
  'Candle making',
  'Canoeing',
  'Canyoning',
  'Capstone Publishers',
  'Car',
  'Card games',
  'Caving',
  'Charity shop',
  'Cheerleading',
  'Cheesemaking',
  'Chess',
  'Chicago Tribune',
  'Climbing',
  'Clothing',
  'Coin collecting',
  'Collecting',
  'Color guard (flag spinning)',
  'Coloring book',
  'Comic Book Collecting Association',
  'Comic book collecting',
  'Competitive dance',
  'Competitive eating',
  'Composting',
  'Computer programming',
  'Confectionery',
  'Contract Bridge',
  'Cooking',
  'Cosplaying',
  'Couponing',
  'Cowles Publishing Company',
  'Craft',
  'Creative writing',
  'Cricket',
  'Crocheting',
  'Cross-stitch',
  'Crossword puzzles',
  'Crown Publishing Group',
  'Cryptography',
  'Cue sports',
  'Curling',
  'Cycling',
  'Daily News (New York)',
  'Daly City, California',
  'Dance',
  'Darts',
  'David Noonan (game designer)',
  'Debate',
  'Deltiology',
  'Diary',
  'Die-cast toy',
  'Digital art',
  'Digital object identifier',
  'Disc golf',
  'Distro-hopping',
  'Do it yourself',
  'Dog sport',
  'Dolls',
  'Dover Publications',
  'Dowsing',
  'Drama',
  'Drawing',
  'Driving',
  'Dungeon Master\'s Guide',
  'ESPNcricinfo',
  'ESports',
  'Education Scotland',
  'Electronics',
  'Element collecting',
  'Embroidery',
  'England Netball',
  'Ephemera',
  'Equestrianism',
  'EuroBillTracker',
  'Exhibition drill',
  'Experimenting',
  'FIDE',
  'Fantasy sport',
  'Fashion',
  'Fashion design',
  'Fencing',
  'Field hockey',
  'Figure skating',
  'Film memorabilia',
  'Fishing',
  'Fishkeeping',
  'Flag football',
  'Flower',
  'Flower arranging',
  'Flying disc',
  'Focal Press',
  'Footbag',
  'Foraging',
  'Forbes',
  'Fossil hunting',
  'Freestyle Football',
  'Freestyle football',
  'Furniture',
  'F\u00e9d\u00e9ration Internationale de Volleyball',
  'Games',
  'Gardening',
  'Genealogy',
  'Geocaching',
  'Ghost hunting',
  'Gingerbread house',
  'Glassblowing',
  'Go (game)',
  'Gold prospecting',
  'Golf',
  'Gongoozler',
  'Graffiti',
  'Graphic design',
  'Greenwood Publishing Group',
  'Gunsmithing',
  'Gymnastics',
  'Handball',
  'Harvard Magazine',
  'Herald Sun',
  'Herbalism',
  'Herpetoculture',
  'Herping',
  'High-power rocketry',
  'Hiking',
  'Hobby',
  'Hobby horse',
  'Hoboken, New Jersey',
  'Home improvement',
  'Home roasting coffee',
  'Homebrewing',
  'Hooping',
  'Horseback riding',
  'Huffington Post',
  'Hula hooping',
  'Human swimming',
  'Hunting',
  'Hydroponics',
  'IPC Media',
  'Ice hockey',
  'Ice skating',
  'Inline skating',
  'Insect collecting',
  'International Cheer Union',
  'International Federation of Gymnastics',
  'International Hockey Federation',
  'International Ice Hockey Federation',
  'International Shooting Sport Federation',
  'International Skating Union',
  'International Standard Book Number',
  'International Yo-Yo Federation',
  'Jewelry making',
  'Jigsaw puzzles',
  'Jogging',
  'John Wiley & Sons',
  'Jonathan Tweet',
  'Judo',
  'Juggling',
  'Jujitsu',
  'Jukskei',
  'Kabaddi',
  'Karaoke',
  'Karate',
  'Kart racing',
  'Katharine Weymouth',
  'Kayaking',
  'Kite',
  'Kitesurfing',
  'Knife collecting',
  'Knife making',
  'Knife throwing',
  'Knitting',
  'Knot tying',
  'Kombucha',
  'LARP Alliance, Inc.',
  'LARPing',
  'Lace',
  'Lacrosse',
  'Lapidary',
  'Laser tag',
  'Lawn Tennis Association',
  'Learning',
  'Leather crafting',
  'Lego',
  'Lerner Publishing Group',
  'Letterboxing (hobby)',
  'Lock picking',
  'Longboarding',
  'Los Angeles Times',
  'Lotology',
  'Machining',
  'Macrame',
  'Magic (illusion)',
  'Magnet fishing',
  'Mahjong',
  'Makeup',
  'Marbles',
  'Marching band',
  'Martial arts',
  'Massachusetts Institute of Technology',
  'Media Wales',
  'Meditation',
  'Melbourne',
  'Metal detecting',
  'Metal detector',
  'Metalworking',
  'Meteorology',
  'Microscopy',
  'Mineral collecting',
  'Mineralogical Society of America',
  'Minneapolis',
  'Mixed drink',
  'Model aircraft',
  'Model building',
  'Model engineering',
  'Monte Cook',
  'Mortimer Zuckerman',
  'Motor sports',
  'Mountain biking',
  'Mountaineering',
  'Movies',
  'Mushroom hunting',
  'Music',
  'Mycology',
  'NBC News',
  'NPR',
  'Nail Art',
  'National Geographic Society',
  'National Ice Skating Association',
  'National Library of Australia',
  'National Operatic and Dramatic Association',
  'Needlepoint',
  'Netball',
  'New York City',
  'News Corp Australia',
  'Newsquest',
  'Newsweek',
  'Nordic skating',
  'Orienteering',
  'Origami',
  'Oxford University Press',
  'Paintball',
  'Painting',
  'Palgrave Macmillan',
  'Parkour',
  'Patch collecting',
  'Penton Media',
  'Perfume',
  'Pet adoption',
  'Philately',
  'Phillumeny',
  'Photography',
  'Podcast',
  'Podcasts',
  'Poi (performance art)',
  'Poker',
  'Polo',
  'Popular Mechanics',
  'Pottery',
  'Powerlifting',
  'Practical jokes',
  'Pressed flower craft',
  'Psylon Press',
  'PubMed Central',
  'PubMed Identifier',
  'Puzzle',
  'Quilling',
  'Quilting',
  'Quizzes',
  'Racquetball',
  'Radio-controlled car',
  'Rafting',
  'Rail transport modeling',
  'Rail transport modelling',
  'Rappelling',
  'Rapping',
  'Reading',
  'Record collecting',
  'Refinishing',
  'Road Cycling',
  'Robot combat',
  'Rock balancing',
  'Rock climbing',
  'Rock tumbling',
  'Role-playing game',
  'Roller derby',
  'Roller skating',
  'Rowing',
  'Rowing (sport)',
  'Royal Aero Club',
  'Royal Caledonian Curling Club',
  'Rubik\'s Cubing',
  'Rugby football',
  'Rugby league',
  'Running',
  'Sailing',
  'Sand art and play',
  'Satellite watching',
  'Scouting',
  'Scrapbooking',
  'Scuba diving',
  'Sculling',
  'Sculpting',
  'Sea glass',
  'Seashell',
  'Second-language acquisition',
  'Sewing',
  'Shoemaking',
  'Shoes',
  'Shogi',
  'Shooting',
  'Shooting sport',
  'Shopping',
  'Shortwave listening',
  'Singing',
  'Skateboarding',
  'Sketch (drawing)',
  'Skiing',
  'Skimboarding',
  'Skip Williams',
  'Skydiving',
  'Slacklining',
  'Slot car racing',
  'Snowboarding',
  'Soapmaking',
  'Soccer',
  'Social media',
  'Softball',
  'South Wales Argus',
  'Speed skating',
  'Speedcubing',
  'Sport stacking',
  'Sports memorabilia',
  'Squash (sport)',
  'Stamp collecting',
  'Stand-up comedy',
  'Stanford University',
  'Stone collecting',
  'Stone skipping',
  'Stuffed toy',
  'Sun bathing',
  'Surfing',
  'Survivalism',
  'Table football',
  'Table tennis',
  'Tabletop game',
  'Taekwondo',
  'Tai chi',
  'Taxidermy',
  'Tea bag',
  'Telegraph Media Group',
  'Telephone card',
  'Television program',
  'Tennis',
  'Tennis polo',
  'Tether car',
  'The Atlantic',
  'The Australian',
  'The Boston Globe',
  'The Daily Mail',
  'The Daily Telegraph',
  'The Economic Times',
  'The Economist',
  'The Free Lance\u2013Star',
  'The Guardian',
  'The Herald (Glasgow)',
  'The Herald and Weekly Times',
  'The Independent',
  'The New York Times',
  'The Philadelphia Inquirer',
  'The Seattle Times',
  'The Spokesman-Review',
  'The State News',
  'The Times',
  'The Times Group',
  'Thomas Register',
  'Ticket (admission)',
  'Time (magazine)',
  'Topiary',
  'Tour skating',
  'Toys',
  'Trading cards',
  'Trainspotting (hobby)',
  'Trapshooting',
  'Travel',
  'Traveling',
  'Triathlon',
  'Tribune Publishing',
  'Ultimate (sport)',
  'University of Massachusetts Press',
  'University of New Mexico',
  'Urban exploration',
  'Vacation',
  'Vegetable farming',
  'Vehicle restoration',
  'Vice Magazine',
  'Video editing',
  'Video game collecting',
  'Video game development',
  'Video gaming',
  'Videophile',
  'Vintage cars',
  'Vintage clothing',
  'Volleyball',
  'Volleyball England',
  'Wales Online',
  'Walking',
  'Wall Street Journal',
  'Washington Post',
  'Water polo',
  'Water sports',
  'Weaving',
  'Weight training',
  'Welding',
  'Whale watching',
  'Whittling',
  'The sun',
  'The moon',
  'The stars',
  'Clouds',
  'Mist/Fog',
  'Snow',
  'Hail',
  'Rain',
  'The ocean',
  'Forests',
  'Mountains',
  'Traveling/Vacation',
  'Shopping',
  'Urban exploring',
  'Abandoned buildings',
  'Gardens/Topiaries',
  'Rivers',
  'Baking/cooking',
  'Mixing drinks',
  'Writing',
  'Photography',
  'tabletops games', 
  'video games',
  'Road trips',
  'red,',
  'orange,',
  'yellow,',
  'green,',
  'blue,',
  'Sports',
  'basketball',
  'football',
  'tennis',
  'horror',
  'comedy',
  'adventure',
  'horror',
  'mystery',
  'fantasy',
  'romance',
  'dogs',
  'cats',
  'sugar gliders',
  'birds',
  'fish,',
  'painting',
  'drawing',
  'spray painting',
  'hot chocolate',
  'fruits',
  'veggies',
  'traditional dishes',
  'Holidays',
  'Learning languages',
  'Sign language',
  'Arabic',
  'French',
  'Polish',
  'English',
  'Collecting Dolls, Collecting keys',
  'Collecting buttons',
  'Collecting stickers',
  'Collecting lip balms',
  'Collecting rocks',
  'Witchcraft',
  'Mythology',
  'Building models',
  'Modeling',
  'Making jewelry',
  'Keeping old tickets and bookmarks',
  'Trying to out-nice your neighbors',
  'Peering out the window',
  'Headphones',
  'Chalk',
  'DIY',
  'Listening to cafe chatter',
  'ocean waves',
  'The ticking of a clock',
  'Nature',
  'Learning',
  'Parades',
  'festivals',
  'farmers markets',
  'Sailing',
  'Flying',
  'New things',
  'Playing/watching pets play in pet friendly packing peanuts.',
  'Curling',
  'Flower pressing',
  'Foraging',
  'Danger',
  'Closed spaces',
  'Open spaces',
  'Hugs',
  'hand holding',
  'PDA',
  'Organization',
  'Mess',
  'Anger',
  'love',
  'disappointment',
  'The feeling of Metal',
  'the feeling of Styrofoam',
  'the feeling of soft blankets',
  'the feeling of slime',
  'the feeling of etc.',
  'Blanket forts',
  'the smell of Perfume/Cologne',
  'fruits',
  'the smell of a new car',
  'collecting cars',
  'watching cars drive by',
  'listening to cars',
  'fixing cars',
  'riding in cars',
  'Repairing items',
  'Card games',
  'Stone/Gravestone rubbing',
  'Nail art',
  'Tutoring',
  'Beekeeping',
  'Interior/Exterior design',
  'Candles',
  'Clay',
  'Making flower crowns',
  'Jumping in puddles',
  'Soap carving',
  'Searching for lost items (in a river, on land, etc.)',
  'Streaming/Social media',
  'Laying on the floor',
  'Incense',
  'inline skating',
  'roller skating',
  'nordic skating',
  'figure skating',
  'Snowboarding',
  'Skiing',
  'playing music',
  'listening to music',
  'creating music',
  'classic dance',
  'freestyle dance',
  'Programming',
  'Volunteering',
  'Reading books to the sick/children/elderly',
  'The setting sun',
  'The rising sun',
  'Picking fruits/veggies',
  'Making dice',
  'Building sets',
  'Lockpicking',
  'Exploring national parks/monuments',
  'Stand up comedy',
  'Decorating',
  'Knick-knacks',
  'Massages',
  'Glowsticks',
  'Throwing rocks',
  'Ugly sweaters',
  'Patterned socks',
  'Certain words ',
  'Certain people',
  'Planning and making lists',
  'Body modification',
  'Piercings',
  'tattoos',
  'hair dyes',
  'Insects/Favorite Bug',
  'Cryptid/ghost hunting',
  'Complaining',
  'Slack lining',
  'Pyrotechnics',
  'Quilting',
  'Sand castles',
  'Storm chasing',
  'Storytelling',
  'Manners/no manners',
  'Blogging',
  'Scrap-booking',
  'Specific days of the week',
  'Trains',
  'Glass blowing',
  'Map making',
  'Snow globes',
  'Posters',
  'Fossils',
  'Comics',
  'Postcards',
  'Bicycling ',
  'Hiking',
  'Climbing',
  'Loud noises',
  'Flashing lights',
  'Fireworks',
  'Seashells',
  'Being late/early/on time',
  'Crowds',
  'Wasting things',
  'Training pets to do tricks',
  'Making dollhouses',
  'Yoga, Pilates, etc.',
  'Poi (performance art)',
  'collecting knives or swords',
  'Camping',
  'Alcohol',
  'Comfortable silence',
  'Surprises',
  'Sincerity',
  'Simplicity',
  'Surfing',
  'Smiles',
  'Freckles, eyes, etc.',
  'Skateboarding',
  'Open meadows',
  'Hills',
  'Cemeteries',
  'Hospitals, museums, etc.',
  'Clubbing',
  'jumping on the bed',
  'jumping on a trampoline',
  'bungee jumping',
  'Diving',
  'cliff diving',
  'sky diving',
  'etc.',
  'Parkour',
  'Hang gliding',
  'Escape rooms',
  'Certain clothes & fashion styles',
  'Canopy beds',
  'Open windows',
  'The sound of birds in the morning',
  'Puzzles',
  'Cleaning',
  'Swings',
  'Fast rides',
  'Amusement/theme/water parks',
  'Lounging in a hammock',
  'Clowns/mimes/puppets, etc.',
  'Martial arts',
  'Showers/baths',
  'Cheerleading ',
  'Canoeing/kayaking/being on the open water.',
  'Fencing/sword fighting',
  'Training pets to do tricks',
  'Pranks',
  'Getting lost',
  'Meditation',
  'Microscopy',
  'Math, science, history, etc.',
  'Long walks, solitary or otherwise',
  'Philosophy',
  'Competition',
  'People watching',
  'Puns',
  'Moshing',
  'Avant garde',
  'Surreal & abstract',
  'Cartoons and certain tv shows',
  'Riddles',
  'Napping',
  'Beach combing',
  'Crafts',
  'Makeup',
  'Makeovers',
  'Zoology',
  'Certain instruments',
  'Getting something in the mail',
  'Cryptozoology',
  'Singing',
  'Acting',
  'Macramé, knitting, crochet, sewing, needlepoint, etc.',
  'Cosplay & costumes',
  'Cold things on hot days and hot things on cold days',
  'Birthdays',
  'Remembering something previously forgotten, like a sound or sensation.',
  'Calligraphy & typography',
  'Antiques',
  'Talking during movies',
  'The sensation of heavy bass',
  'Bells',
  'Inventing',
  'Juggling',
  'Keeping journals/diaries',
  'Kites',
  'Wind chimes',
  'Horse riding',
  'Woodworking',
  'Farming',
  'Fishing',
  'Hair styling',
  'Motocross',
  'Fitted clothing',
  'Loose/over-sized clothing',
  'Knapping (not napping)',
  'Visiting distant friends/family',
  'Being alone',
  'Gyotaku ',
  'Herping ',
  'Staying inside',
  'Going outside',
  'Astrology',
  'Falconry',
  'Genealogy',
  'Gnome collecting ',
  'Tarot card readings',
  'Guessing something correctly',
  'Arguing',
  'Lightning',
  'Fireplaces',
  'Falling leaves',
  'Waking late or early',
  'Attending plays/musicals (theatre in general)',
  'Planes',
  'Origami',
  'Yo-yos',
  'Children',
  'Drama',
  'Politics',
  'Facial hair',
  'Leather',
  'Money',
  'Falling in love',
  'Dominoes',
  'Dumpster diving',
  'Technology',
  'Heights',
  'Gossip',
  'Paleontology',
  'Westerns ',
  'Stuffed animals',
  'Meteorology',
  'Extravagant things, clothes, etc.',
  'Anthropology',
  'Psychology',
  'Fungi',
  'Metalworking',
  'Celebrities',
  'Treasure hunting',
  'Economics',
  'Pottery',
  'Coloring',
  'Conspiracy theories',
  'Fairy tales',
  'Apocalypse films/books',
  'Pocket watches',
  'Alchemy',
  'Jump rope',
  'Flirting',
  'LARP',
  'Hunting',
  'Statues',
  'Mannequins',
  'Sculpting',
  'Umbrellas/parasols',
  'Riding in the truck bed',
  'Sleeping in a car/truck bed',
  'Making soaps/candles',
  'Stationary',
  'Listening to podcasts/people talking',
  'Multitasking',
  'Spirals',
  'plaid',
  'Inactivity',
  'Repetition/routine',
  'Sudden movements',
  'Writing letters',
  'Superheroes',
  'Eldritch monsters',
  'Hot air balloons',
  'Coffee mugs',
  'Action figures/figurines in general',
  'Pirates',
  'Tea sets',
  'Gymnastics',
  'Making clothes',
  'Smithing',
  'Renaissance',
  'Steampunk',
  'Cyberpunk',
  'Architecture',
  'Vinyl records',
  'Obscure trivia',
  'Jewelry',
  'Scarecrows',
  'Mazes',
  'Laser tag',
  'Paintball',
  'Knife throwing',
  'Go (the game), chess, strategy games',
  'Strategy (in general)',
  'Bowling',
  'Darts',
  'Documentaries',
  'Racing cars/watching races',
  'Robotics',
  'Archery',
  'Bird watching',
  'Cake decorating',
  'Cave exploring',
  'Dating (With or without the commitment; i.e might enjoy the aspect of dating, but not having a partner) ',
  'Hardwood/carpet floors',
  'Cold/hot water',
  'Fiddling with items',
  'Being wanted/needed',
  'Creating written/spoken codes',
  'inventing things',
  'inventing languages',
  'Walking around with bare feet/wearing socks.',
  'Giving gifts/receiving gifts.',
  'Deadpan humor.',
  'Necromancy.',
  'Hiding',
  'Writing/finding fortunes',
];
